name = "whenismtrain"
main = "./.cloudflare/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
build.command = "npm run build"
assets.directory = ".cloudflare/public"
assets.binding = "ASSETS"
